-- 스칼라 질의
-- 구매한 고객의 모든 정보을 보이시오

select * 
from customer cs, orders od
where (cs.custid = od.custid);

SELECT * FROM CUSTOMER CS
INNER JOIN ORDERS OD
ON CS.CUSTID = OD.CUSTID;

-- 고객별 판매액을 검색하여 해당 고객의 이름과 판매총액을 보이시오
SELECT NAME, SUM(SALEPRICE)
FROM CUSTOMER CS
INNER JOIN ORDERS OD
ON CS.CUSTID = OD.CUSTID
GROUP BY CS.NAME
ORDER BY CS.NAME;

-- 스칼라 질의 사용
SELECT OD.CUSTID, (SELECT NAME FROM CUSTOMER CS WHERE CS.CUSTID = OD.CUSTID) NAME, SUM(SALEPRICE)
FROM ORDERS OD
GROUP BY OD.CUSTID;

-- 각 도서의 출판사 평균 가격과 비교해서. 그 책이 평균보다 비싼지 여부 표시
SELECT BOOKID, BOOKNAME, PRICE,
    (SELECT AVG(PRICE) FROM BOOK B2
     WHERE B2.PUBLIISHER = B1.PUBLISHER) AS AVG_PRICE,
     CASE
      WHEN PRICE >= (SELECT AVG(PRICE)FROM BOOK B3
      WHERE B3.PUBLISHER = B1.PUBLISHER)
      THEN '비쌈'
      ELSE '저렴/보통'
    END AS PRICE_LEVEL
FROM BOOK B1;

-- 고객마다 마지막 주문일 출력
SELECT * FROM ORDERS;

SELECT CUSTID, NAME,
(SELECT MAX(ORDERDATE) FROM ORDERS OD WHERE CS.CUSTID = OD.CUSTID) AS LAST_ORDER
FROM CUSTOMER CS;
















